#!/usr/bin/env ruby
# frozen_string_literal: true

# paneful FILE [SCREEN]                 run the dashboards defined in FILE
# paneful --snapshot FILE [SCREEN]      print one frame as plain text and exit
#   --width N --height N --ticks N      snapshot size, and how many refreshes to take first

require "optparse"
require_relative "../lib/paneful"

options = { snapshot: false, width: 120, height: 40, ticks: 2 }
parser = OptionParser.new do |o|
  o.banner = "Usage: paneful [--snapshot] FILE [SCREEN]"
  o.on("--snapshot", "Print one frame and exit") { options[:snapshot] = true }
  o.on("--width N", Integer) { |n| options[:width] = n }
  o.on("--height N", Integer) { |n| options[:height] = n }
  o.on("--ticks N", Integer) { |n| options[:ticks] = n }
end
file, screen = parser.parse(ARGV)
abort(parser.banner) unless file

load File.expand_path(file)
if options[:snapshot]
  puts Paneful.snapshot(screen, width: options[:width], height: options[:height], ticks: options[:ticks])
else
  Paneful.run(screen)
end
